
import { CalendarDays, Clock3, BedDouble, Stethoscope, HeartPulse, FlaskConical, ScanLine, Pill, ReceiptText, Boxes, FileText, Plus } from "lucide-react";

export function GenericModuleView({ active }: { active: string }) {
  const config: Record<string, any> = {
    "Appointments": {
      title: "Appointments & Scheduling", desc: "Manage upcoming visits, telehealth, and in-person consultations.",
      cols: ["Time", "Patient", "Doctor", "Type", "Status"],
      rows: [
        ["09:00 AM", "Ananya Rao", "Dr. Sharma", "Follow-up", "Completed"],
        ["09:30 AM", "Rajesh Kumar", "Dr. Iyer", "Initial Consult", "In Progress"],
        ["10:00 AM", "Priya Singh", "Dr. Mehta", "Telehealth", "Waiting"],
        ["10:15 AM", "Amit Patel", "Dr. Sharma", "Follow-up", "Waiting"],
      ]
    },
    "OPD": {
      title: "Outpatient Department (OPD)", desc: "Live tracking of walk-in and scheduled OPD consultations.",
      cols: ["Token", "Patient", "Vitals", "Assigned Doctor", "Status"],
      rows: [
        ["A-102", "Sunita Verma", "BP: 120/80, HR: 72", "Dr. Iyer", "Consulting"],
        ["A-103", "Vikram Malhotra", "BP: 135/85, HR: 88", "Dr. Iyer", "Waiting"],
        ["B-041", "Neha Gupta", "BP: 118/76, HR: 65", "Dr. Sharma", "Waiting"],
      ]
    },
    "IPD & Beds": {
      title: "Inpatient & Bed Management", desc: "Real-time occupancy, transfers, and bed turnover.",
      cols: ["Bed ID", "Ward", "Patient", "Admitted", "Status"],
      rows: [
        ["ICU-01", "Intensive Care", "Ramesh Das", "2 Days ago", "Occupied"],
        ["ICU-02", "Intensive Care", "—", "—", "Available"],
        ["GEN-14", "General Ward A", "Kavita Nair", "4 Days ago", "Occupied"],
        ["GEN-15", "General Ward A", "—", "—", "Cleaning"],
      ]
    },
    "Doctors": {
      title: "Doctor Roster", desc: "Live availability and shift management for medical staff.",
      cols: ["Doctor", "Department", "Shift", "Current Location", "Status"],
      rows: [
        ["Dr. Rajesh Sharma", "Cardiology", "Morning", "OPD Room 4", "Consulting"],
        ["Dr. Priya Iyer", "Neurology", "Morning", "ICU", "Rounding"],
        ["Dr. Amit Mehta", "Orthopedics", "Off Duty", "—", "Off"],
      ]
    },
    "Nursing": {
      title: "Nursing Station", desc: "Shift handovers, ward assignments, and critical alerts.",
      cols: ["Nurse", "Ward Assignment", "Shift", "Patients", "Status"],
      rows: [
        ["Sister Mary", "ICU", "Morning", "4", "Active"],
        ["Nurse Jacob", "General Ward A", "Morning", "12", "Active"],
        ["Nurse Anita", "Emergency", "Morning", "8", "Busy"],
      ]
    },
    "Laboratory": {
      title: "Laboratory & Diagnostics", desc: "Process pathology, hematology, and biochemistry requests.",
      cols: ["Req ID", "Patient", "Test Type", "Sample", "Status"],
      rows: [
        ["LAB-8901", "Ananya Rao", "Complete Blood Count", "Collected", "Processing"],
        ["LAB-8902", "Rajesh Kumar", "Lipid Profile", "Pending", "Awaiting Sample"],
        ["LAB-8903", "Vikram Malhotra", "HbA1c", "Collected", "Completed"],
      ]
    },
    "Radiology": {
      title: "Radiology & Imaging", desc: "Manage X-Ray, MRI, CT Scans, and Ultrasound queues.",
      cols: ["Scan ID", "Patient", "Modality", "Referring Dr", "Status"],
      rows: [
        ["RAD-402", "Sunita Verma", "Chest X-Ray", "Dr. Iyer", "Ready for Review"],
        ["RAD-403", "Kavita Nair", "MRI Brain", "Dr. Sharma", "In Progress"],
      ]
    },
    "Pharmacy": {
      title: "Pharmacy & Dispensary", desc: "Prescription fulfillment and stock alerts.",
      cols: ["Prescription", "Patient", "Items", "Payment", "Status"],
      rows: [
        ["RX-9921", "Ananya Rao", "3 Items", "Cleared", "Dispensed"],
        ["RX-9922", "Ramesh Das", "5 Items", "Pending", "Processing"],
      ]
    },
    "Billing": {
      title: "Billing & Insurance", desc: "Invoices, claims, and revenue cycle management.",
      cols: ["Invoice #", "Patient", "Amount", "Insurance", "Status"],
      rows: [
        ["INV-2041", "Ananya Rao", "? 1,500", "HDFC ERGO", "Paid"],
        ["INV-2042", "Ramesh Das", "? 45,000", "Star Health", "Claim Pending"],
      ]
    },
    "Inventory": {
      title: "Inventory & Supply Chain", desc: "Monitor stock levels for medical and surgical supplies.",
      cols: ["Item Code", "Category", "Item Name", "Stock Level", "Status"],
      rows: [
        ["SUP-01", "Surgical", "Latex Gloves (M)", "4,500 Box", "Optimal"],
        ["MED-44", "Medicine", "Paracetamol 500mg", "120 Strips", "Low Stock"],
        ["EQP-12", "Equipment", "Syringes 5ml", "10 Box", "Critical"],
      ]
    },
    "Reports": {
      title: "Analytics & Reports", desc: "Generate clinical, operational, and financial reports.",
      cols: ["Report Name", "Category", "Generated By", "Date", "Status"],
      rows: [
        ["Daily Revenue Summary", "Financial", "System", "Today, 08:00 AM", "Ready"],
        ["ICU Mortality Rate Q3", "Clinical", "Dr. Zarro", "Yesterday", "Ready"],
      ]
    }
  };

  const data = config[active];
  if (!data) return null;

  return (
    <section className="page-view glass">
      <header className="page-header">
        <div>
          <h2>{data.title}</h2>
          <p>{data.desc}</p>
        </div>
        <button className="primary" type="button"><Plus size={18} /> New Entry</button>
      </header>
      <div className="table-wrap full-height">
        <table>
          <thead>
            <tr>
              {data.cols.map((c: string) => <th key={c}>{c}</th>)}
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {data.rows.map((row: string[], i: number) => (
              <tr key={i}>
                {row.map((cell: string, j: number) => (
                  <td key={j} className={cell === "Critical" || cell === "Low Stock" ? "red" : ""}>
                    {j === 1 || j === 0 ? <strong>{cell}</strong> : cell}
                  </td>
                ))}
                <td>
                  <div className="action-buttons">
                    <button className="row-action" type="button">View</button>
                    <button className="row-action" type="button">Edit</button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

