"use client";
import { useEffect, useState } from "react";

const sections = [
  ["Problem", "Hospital workflows lose context across handoffs, departments, and unreliable connectivity."], ["Architecture", "Identity → policy → command → workflow → event → audit → projection."], ["Reliability", "Run seven visible failure attacks and inspect the persisted outcome."], ["Security", "Organization-scoped access, role permissions, idempotency, and expected-version writes."], ["AI guardrails", "Madhu supports summaries, navigation, explanation, and drafts; it does not diagnose or prescribe."], ["Limitations", "Prototype only: no clinical diagnosis, prescribing, compliance certification, or real-patient use. Demo data is deterministic where labelled."],
];
type Metrics = { tenant: string; heroPatient: { id: string; name: string } | null; persistedEvents: number; persistedAudits: number; latestRun: { scenarios: number; passed: number; events: number; audits: number; generatedAt: string } | null };

export default function JudgeMode() {
  const [metrics, setMetrics] = useState<Metrics | null>(null); const [message, setMessage] = useState<string | null>(null); const [seeding, setSeeding] = useState(false);
  async function refresh() { const response = await fetch("/api/judge/metrics"); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Live judge metrics are unavailable."); setMetrics(body); }
  useEffect(() => { void refresh().catch((error) => setMessage(error instanceof Error ? error.message : "Live judge metrics are unavailable.")); }, []);
  async function seed() { setSeeding(true); setMessage(null); try { const response = await fetch("/api/demo/seed", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Demo seed failed."); await refresh(); setMessage(`Demo tenant reset: ${body.heroPatient.name} with ${body.events} events and ${body.audits} audits.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Demo seed failed."); } finally { setSeeding(false); } }
  return <main style={{ minHeight: "100vh", background: "#101917", color: "#eff8f1", padding: "52px clamp(20px, 9vw, 160px)", fontFamily: "Arial, sans-serif" }}>
    <p style={{ color: "#8de9ae", fontSize: 12, letterSpacing: 2 }}>HOSPITALX / JUDGE MODE</p><h1 style={{ fontSize: "clamp(42px, 8vw, 88px)", margin: "8px 0" }}>One patient.<br />One story.<br />One trace.</h1><p style={{ color: "#c0cec4", maxWidth: 690, fontSize: 19, lineHeight: 1.6 }}>A guided proof path for hospital workflow integrity under ordinary work and operational stress.</p>
    <nav style={{ display: "flex", gap: 12, flexWrap: "wrap", margin: "28px 0" }}><button onClick={seed} disabled={seeding} style={{ background: "#8de9ae", color: "#102219", padding: "12px 16px", borderRadius: 8, fontWeight: 800, border: 0 }}>{seeding ? "RESETTING DEMO…" : "RESET DEMO TENANT"}</button><a href="/reliability" style={{ background: "#8de9ae", color: "#102219", padding: "12px 16px", borderRadius: 8, fontWeight: 800, textDecoration: "none" }}>RUN RELIABILITY LAB</a><a href="/verify" style={{ border: "1px solid #8de9ae", color: "#eff8f1", padding: "12px 16px", borderRadius: 8, fontWeight: 800, textDecoration: "none" }}>OPEN VERIFIER</a></nav>
    {message && <p role="status" style={{ border: "1px solid #476b54", padding: 12, borderRadius: 10, color: "#c0cec4" }}>{message}</p>}
    <section aria-label="Live demo evidence" style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 14, margin: "28px 0" }}><article style={{ padding: 18, border: "1px solid #31463a", borderRadius: 14, background: "#15221d" }}><small style={{ color: "#8de9ae" }}>DEMO TENANT</small><p style={{ fontSize: 20, margin: "8px 0" }}>{metrics?.tenant ?? "Loading…"}</p><small>{metrics?.heroPatient ? `Hero patient: ${metrics.heroPatient.name}` : "Reset the demo to create the hero journey."}</small></article><article style={{ padding: 18, border: "1px solid #31463a", borderRadius: 14, background: "#15221d" }}><small style={{ color: "#8de9ae" }}>PERSISTED PROOF</small><p style={{ fontSize: 20, margin: "8px 0" }}>{metrics ? `${metrics.persistedEvents} events · ${metrics.persistedAudits} audits` : "Loading…"}</p><small>Counts are read from the database, not browser state.</small></article><article style={{ padding: 18, border: "1px solid #31463a", borderRadius: 14, background: "#15221d" }}><small style={{ color: "#8de9ae" }}>LATEST LAB RUN</small><p style={{ fontSize: 20, margin: "8px 0" }}>{metrics?.latestRun ? `${metrics.latestRun.passed} / ${metrics.latestRun.scenarios} held` : "No run recorded"}</p><small>{metrics?.latestRun ? `${metrics.latestRun.events} events · ${metrics.latestRun.audits} audits · ${new Date(metrics.latestRun.generatedAt).toLocaleString()}` : "Run the Reliability Lab to produce live judge metrics."}</small></article></section>
    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 14 }}>{sections.map(([title, text], index) => <article key={title} style={{ padding: 20, border: "1px solid #31463a", borderRadius: 14, background: "#15221d" }}><p style={{ color: "#8de9ae", margin: 0 }}>0{index + 1}</p><h2>{title}</h2><p style={{ color: "#c0cec4", lineHeight: 1.5 }}>{text}</p></article>)}</section>
  </main>;
}
